# Generated by Django 6.1 on 2026-09-10 15:11

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='category',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='started_since',
        ),
        migrations.AddField(
            model_name='hobby',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hobby',
            name='icon_or_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
