# Generated by Django 6.1 on 2026-09-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
