# Generated by Django 6.1 on 2026-09-21 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_experience_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
    ]
