# Generated by Django 6.1 on 2026-09-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_experience_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='status',
        ),
    ]
