# Generated by Django 6.1 on 2026-09-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_experience_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Artwork',
        ),
    ]
